<?php
/**
 * Created by PhpStorm.
 * User: Julius Alvarado
 * Date: 5/21/2020
 * Time: 6:59 AM
 */


/**
 * Created by PhpStorm.
 * User: Julius Alvarado
 * Date: 8/25/2019
 * Time: 2:35 AM
 *
 *
 * - This is the VERY simple UI so the user can type something
 * a textarea input form to emulate client and data instructions
 *
 * Primarily this is good for a human to test, not phpunit.
 *
 */

$appName = "Code Buddies Connect";

?>


<!DOCTYPE html>

<html lang="en" data-ng-app="cbConnectApp">

<head>
    <meta charset="UTF-8">
    <title>Code Buddies connect</title>

    <!-- Angular Material CSS now available via Google CDN; version 1.1.9 used here -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.css">
    <link rel="stylesheet" href="/ui-match/styles/app.css">

    <!-- ng-cloak -->
    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>
</head>


<body ng-controller="MatchCtrl">

<!-- Horizontal sort of Nav Bar -->
<?php
include 'templates/layout/toolbar.php'
?>

<!-- _SESSION TEST -->
<p>{{status}}</p>
<br>
<?= $data['codeUser'] ?? 'no code buddy user' ?>
<br>
<?= $_SESSION['j_user'] ?? 'no j_user' ?>

<div layout="row" layout-align="center center">
    <!-- LEFT side -->
    <div layout-padding flex="15">
        <!-- icon looking -->
        <div layout="row" layout-align="center center">
            <ng-md-icon icon="nature_people" style="fill: forestgreen" size="36"></ng-md-icon>
            <h1>&nbsp; Looking</h1>
        </div>

        <h1 class="cb-text-center cb-mtop-0">1 / 3
            <ng-md-icon icon="check_circle" style="fill: hotpink"></ng-md-icon>
        </h1>
    </div>

    <!-- RIGHT side -->
    <div class="md-padding checkboxdemoBasicUsage" ng-cloak flex="60">
        <form action="/test/get-matched/about-user" method="POST">
            <h1>You are looking for</h1>

            <fieldset class="standard">
                <div layout-wrap layout-gt-sm="row">
                    <!-- 1st option -->
                    <div flex-gt-sm="50">
                        <!--  {{ data.cb1 }} -->
                        <md-checkbox ng-model="data.account" aria-label="Checkbox 1">
                            Accountability Partner
                        </md-checkbox>
                    </div>

                    <!-- 2nd option -->
                    <div flex-gt-sm="50">
                        <!-- md-warn  ng-false-value="'nope'"   ng-true-value="'yup'" {{ data.cb2 }} -->
                        <md-checkbox ng-model="data.coding" aria-label="Checkbox 2" class="md-align-top-left">
                            Coding Partner
                        </md-checkbox>
                    </div>

                    <!-- 3rd option -->
                    <div flex-gt-sm="50">
                        <!-- ng-disabled="true" aria-label="Disabled checkbox" -->
                        <md-checkbox ng-model="data.mentor" aria-label="Checkbox 3">
                            Mentor (I am looking for a mentor)
                        </md-checkbox>
                    </div>

                    <!-- 4th option -->
                    <div flex-gt-sm="50">
                        <!-- ng-disabled="true" aria-label="Disabled checked checkbox" -->
                        <md-checkbox ng-model="data.mentee" aria-label="Checkbox 4" ng-init="data.mentee=true">
                            Mentee (I would like to mentor or teach)
                        </md-checkbox>
                    </div>

                    <!-- 5th option -->
                    <div flex-gt-sm="50">
                        <md-checkbox ng-model="data.openSource" aria-label="Checkbox 5">
                            Open Source Project to contribute to
                        </md-checkbox>
                    </div>

                    <!-- 6th option -->
                    <div flex-gt-sm="50">
                        <!-- md-indeterminate="" aria-label="Checkbox Indeterminate" -->
                        <md-checkbox ng-model="data.contributors" aria-label="Checkbox 6">
                            Contributors for Open Source Project
                        </md-checkbox>
                    </div>

                    <!-- Other option -->
                    <div flex-gt-sm="50">
                        <!--  md-indeterminate="" aria-label="Checkbox Disabled Indeterminate" ng-disabled="true" -->
                        <md-checkbox ng-model="data.other" aria-label="Checkbox last">
                            Other (not mentioned above)
                        </md-checkbox>
                    </div>
                </div>
            </fieldset>

            <h1 class="cb-text-center">Please provide more detail</h1>

            <md-input-container class="md-block">
                <label>What you're working on, struggling with, looking for someone who?</label>
                <textarea name="working-on" ng-model="user.biography" md-maxlength="500" rows="5"
                          md-select-on-focus=""></textarea>
            </md-input-container>

            <!-- The _HIDDEN fields -->
            <input type="hidden" id="{{code-user}}" name="code-user" value="<?= $data['codeUser'] ?? null ?>">
            <input type="hidden" value="{{data.account}}" name="account">
            <input type="hidden" value="{{data.coding}}" name="coding">
            <input type="hidden" value="{{data.mentor}}" name="mentor">
            <input type="hidden" value="{{data.mentee}}" name="mentee">
            <input type="hidden" value="{{data.openSource}}" name="openSource">
            <input type="hidden" value="{{data.contributors}}" name="contributors">
            <input type="hidden" value="{{data.hackTeamToJoin}}" name="hackTeamToJoin">
            <input type="hidden" value="{{data.joinMyHackTeam}}" name="joinMyHackTeam">
            <input type="hidden" value="{{data.other}}" name="other">

            <div layout="row" layout-align="end start">
                <md-button class="md-raised md-accent md-hue-4 cb-btn" type="submit">
                    Next, Your Skills
                </md-button>
            </div>
        </form>
    </div>
</div>

<br><br>

<?php
include 'templates/layout/footer.php';
?>


<!-- Angular Material Dependencies -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-animate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-aria.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-messages.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.7.1/angular-material-icons.min.js"></script>

<!-- Angular Material Javascript now available via Google CDN; version 1.1.9 used here -->
<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.js"></script>

<!-- The AngularJS 1.7 app -->
<script src="/ui-match/app.js"></script>


</body>
</html>