<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Data Application</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            margin: 12px 0 0 0;
            color: #aaa;
            font-size: 18px;
            padding: 20px;
        }

        .landing {
            padding: 0;
            width: 100%;
            text-align: center;
            margin-bottom: 64px;
        }

        .landing > h1 {
            color: #32ace7;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        @media screen and (max-width: 700px) {
            .landing > h1 {
                font-size: 60px;
            }
        }
    </style>
</head>


<body>

<div class="landing">
    <h1>Code Buddies Connect API</h1>
    <h4>Powered by PHP, SQL, and Google Cloud</h4>

    <?php if (isset($name)) : ?>
        <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
    <?php else: ?>
        <p><a href="http://www.codebuddies.org">Code Buddies</a></p>
    <?php endif; ?>
</div>

</body>
</html>
